export type AppPage =
  | "home"
  | "library"
  | "games"
  | "store"
  | "store-detail"
  | "achievements"
  | "activity"
  | "verification"
  | "settings"
  | "game-details"
  | "library-game-detail"
  | "global-search"
  | "console"
  | "launcher-achievements";